### ISSUE TITLE
Supporting more file types / Improve legend for graph export

### ISSUE THREAD

**Issue by Amy-yue-cheng** [mimurrayy/OES-toolbox#1]
1. we have different type of spectrum data like .fits from ICCD, and .RWD8 from avantes ,(ICCD data is pixel and we use our own program to convert to wavelength, and for avantes data it has headers and different commas or semicolons) which we use quite offen, but the oes tool can not recognize them, we would hoping that maybe you want to add these kind of files in to the oes tool?
2. I try to save the graph and paste into power point for example, but the label become really large and covered spectral line. Is this my problem?
![image](https://github.com/user-attachments/assets/c0dba6cc-9c43-42ed-b480-6628f43c1a08)
3. And is it possible to only zoom in by x-axis?
4. Thank you very much

**Comment by mimurrayy** [comment]
Hi Amy!

1. Yes, I'm very interested to support as many common file types as possible. I can always figure out text files, but for binary files like RWD8, it can be very difficult. For text files, just send me the file here and I will figure it out. For binary files, I can give it a try (still need an example file!), put I won't make any promises. The other option is that you figure it out yourself and send me the file and a python example on how to load it. In this case I would definitely add it to the software. 
For what it's worth: Avantes raw8 files are already supported. No idea why they need to have multiple different file formats...

2.  I'm going to have a look at improving this, but the automatic graph export will never work perfectly under all circumstances and will always have either too little or too much information in the legend. If you need to make a nice graph, you can use File->Export->Plot Data, which will export anything shown in the graph as a text file so you can just plot the results yourself. 

3. Yes! If you hold down the right mouse button on the graph and move left-right it zooms in/out on the X-axis only. It's a bit of an awkward control scheme initially (not my idea, the graph view is a standard component that I'm just using) but once you get used to it, it works very well. Give it a try. Alternatively, right clicking the graph view opens up a menu with many more setting, where you can also set the axis limits manually, if needed. 

Cheers,
Julian

**Comment by Amy-yue-cheng** [comment]
Dear Julian

 

1.For RWD8 file what we do now, is convert to TXT on Avantes’s software and then use python to filter the data that we want.

Enlosed you can find our RWD8 file , converted TXT and the scripts.(my mail box does not allow me to send .py. so I put them into TXT file.)

For fits, we use matlab to convert the data.

2.Thanks, I have already tried, it success.

3.It works really well.

Thanks a lot.

_ _ _ _ _ _ _ _ 

Viele Grüße
Yue Cheng
Ruhr-Universität Bochum | D-44801 Bochum

Universitätsstr. 150 | Fakultät für Physik und Astronomie 

Experimentalphysik II | Gebäude NB 5/172  
Email: ***@***.*** ***@***.***>

**Comment by Amy-yue-cheng** [comment]
I forgot one file that is converted .TXT from RWD8 on Avantes.

 

From: Amy.Chengy ***@***.***> 
Sent: Wednesday, September 4, 2024 3:58 PM
To: 'mimurrayy/OES-toolbox' ***@***.***>
Cc: ***@***.***' ***@***.***>
Subject: RE: [mimurrayy/OES-toolbox] issue about oes tool (Issue #1)

 

Dear Julian

 

1.For RWD8 file what we do now, is convert to TXT on Avantes’s software and then use python to filter the data that we want.

Enlosed you can find our RWD8 file , converted TXT and the scripts.(my mail box does not allow me to send .py. so I put them into TXT file.)

For fits, we use matlab to convert the data.

2.Thanks, I have already tried, it success.

3.It works really well.

Thanks a lot.

_ _ _ _ _ _ _ _ 

Viele Grüße
Yue Cheng
Ruhr-Universität Bochum | D-44801 Bochum

Universitätsstr. 150 | Fakultät für Physik und Astronomie 

Experimentalphysik II | Gebäude NB 5/172  
Email: ***@***.*** ***@***.***>

**Comment by mimurrayy** [comment]
Hi Amy,

The avantes text file you sent me seems to work without any problems on my side. Are you sure it's not working for you? If you want me to look at the other files, please send them to me. You might want to use the github interface online instead of email, then you won't have a problem with attaching files.

Cheers,
Julian

**Comment by mimurrayy** [comment]
Closing with the following solutions:
1. I think these files should work. If not, please re-open and send me the files, here or via direct email.
2. Solved by writing documentation: https://github.com/mimurrayy/OES-toolbox/wiki/Usage#graph-and-data-export
3. Solved by writing documentation: https://github.com/mimurrayy/OES-toolbox/wiki/Usage#graph-view

If there was a misunderstanding and the problems are _not_ solved, please let me know!
